### ISSUE TITLE
Save effects committed code bug

### ISSUE THREAD

**Issue by Mattallmighty** [Mattallmighty/LedFx#2]
Clicking on "pitchSpectrium" get the following error: 

```
Traceback (most recent call last):
  File "d:\google drive\ledfx\ledfx-master-mattallmighty\ledfx-master\ledfx\effects\audio.py", line 133, in _audio_sample_callback
    self._invoke_callbacks()
  File "d:\google drive\ledfx\ledfx-master-mattallmighty\ledfx-master\ledfx\effects\audio.py", line 140, in _invoke_callbacks
    callback()
  File "d:\google drive\ledfx\ledfx-master-mattallmighty\ledfx-master\ledfx\effects\audio.py", line 454, in _audio_data_updated
    self.audio_data_updated(self.audio)
  File "d:\google drive\ledfx\ledfx-master-mattallmighty\ledfx-master\ledfx\effects\pitchSpectrum.py", line 48, in audio_data_updated
    note_color = self.get_gradient_color(midi_scaled)
  File "d:\google drive\ledfx\ledfx-master-mattallmighty\ledfx-master\ledfx\effects\gradient.py", line 128, in get_gradient_color
    return self._gradient_curve[:, point]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
[2019-09-10 20:51:36] ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "C:\Users\Matt\Anaconda3\envs\ledfx-not-matt\lib\site-packages\aiohttp-3.3.2-py3.6-win-amd64.egg\aiohttp\web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "C:\Users\Matt\Anaconda3\envs\ledfx-not-matt\lib\site-packages\aiohttp-3.3.2-py3.6-win-amd64.egg\aiohttp\web_app.py", line 341, in _handle
    resp = await handler(request)
  File "d:\google drive\ledfx\ledfx-master-mattallmighty\ledfx-master\ledfx\api\__init__.py", line 26, in handler
    return await method(**{arg_name: available_args[arg_name] for arg_name in wanted_args})
  File "d:\google drive\ledfx\ledfx-master-mattallmighty\ledfx-master\ledfx\api\device_effects.py", line 63, in put
    config_dir = self._ledfx.config_dir)
  File "d:\google drive\ledfx\ledfx-master-mattallmighty\ledfx-master\ledfx\config.py", line 95, in save_config
    yaml.dump(config, file, default_flow_style=False)
IndexError
Stopping LedFx.

(ledfx-not-matt) C:\Users\Matt>
```

**Comment by Mattallmighty** [comment]
https://github.com/Mattallmighty/LedFx/projects/1#card-26239919
