### ISSUE TITLE
Error during "add new device" - blank white page in frontend

### ISSUE THREAD

**Issue by lechk82** [Mattallmighty/LedFx#4]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_app.py", line 341, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/dist-packages/ledfx-0.3-py3.6.egg/ledfx/api/__init__.py", line 26, in handler
    return await method(**{arg_name: available_args[arg_name] for arg_name in wanted_args})
  File "/usr/local/lib/python3.6/dist-packages/ledfx-0.3-py3.6.egg/ledfx/api/schema.py", line 20, in get
    for device_type, device in self._ledfx.devices.classes().items():
AttributeError: 'LedFxCore' object has no attribute 'devices'`

**Comment by Mattallmighty** [comment]
yes this is currently in development, a while to go on this
