### ISSUE TITLE
When i open ledfx by anconda, i ve got this error

### ISSUE THREAD

**Issue by tihoangyeudau** [Mattallmighty/LedFx#5]
(base) C:\Users\tuant>conda activate ledfx

(ledfx) C:\Users\tuant>ledfx --open-ui
Loading configuration file from C:\Users\tuant\AppData\Roaming\.ledfx
Traceback (most recent call last):
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\site-packages\voluptuous\schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\site-packages\voluptuous\schema_builder.py", line 553, in validate_dict
    raise er.DictInvalid('expected a dictionary', path)
voluptuous.error.DictInvalid: expected a dictionary

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\tuant\Anaconda3\envs\ledfx\Scripts\ledfx.exe\__main__.py", line 9, in <module>
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\site-packages\ledfx\__main__.py", line 88, in main
    ledfx = LedFxCore(config_dir = args.config)
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\site-packages\ledfx\core.py", line 23, in __init__
    self.config = load_config(config_dir)
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\site-packages\ledfx\config.py", line 87, in load_config
    return CORE_CONFIG_SCHEMA(yaml.load(file))
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\site-packages\voluptuous\schema_builder.py", line 271, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: expected a dictionary

**Comment by tihoangyeudau** [comment]
mattallmighty:
Windows fix C:\Users\mattremote\AppData\Roaming.ledfx and delete config.yaml
should fix it
