### ISSUE TITLE
i have this issue: ModuleNotFoundError: No module named 'ledfx.devices.lib'

### ISSUE THREAD

**Issue by tihoangyeudau** [Mattallmighty/LedFx#6]
(ledfx) C:\Users\tuant>ledfx --open-ui
Loading configuration file from C:\Users\tuant\AppData\Roaming\.ledfx
Started webinterface at http://127.0.0.1:8888
[2019-10-15 17:06:45] ERROR:ledfx.core:Exception in core event loop: Task exception was never retrieved
Traceback (most recent call last):
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\site-packages\ledfx\core.py", line 91, in async_start
    self.devices = Devices(self)
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\__init__.py", line 160, in __init__
    super().__init__(ledfx, Device, self.PACKAGE_NAME)
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\site-packages\ledfx\utils.py", line 189, in __init__
    self.import_registry(package)
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\site-packages\ledfx\utils.py", line 225, in import_registry
    importlib.import_module(name)
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\fadecandy.py", line 6, in <module>
    from ledfx.devices.lib.opc import Client
ModuleNotFoundError: No module named 'ledfx.devices.lib'

**Comment by NicodimarcoTV** [comment]
Hey I got this Problem Fixed by copying the complete `ledfx` folder into `/usr/local/lib/python3.6/dist-packages/ledfx-0.3-py3.6.egg/`

**Comment by hediondo1** [comment]
i have the same issue on windows 10
